services:
  api_auth:
    container_name: auth_backend
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: unless-stopped

    volumes:
      - auth.db:/data/auth.db

volumes:
  auth.db:
    driver: local